var:
  url-repo: https://github.com/ludo2ne/ENSAI-3A-Master-STD   # to call this value : {{< meta var.url-repo >}}

project:
  type: website

website:
  title: "Master STD"
  repo-url: "{{< meta var.url-repo >}}"
  repo-branch: main
  reader-mode: true
  navbar:
    background: "#124A61"
    left:
      - href: index.qmd
        text: Home
      - href: doc/presentation.qmd
        text: Présentation
      - text: Le Master
        menu:
          - href: doc/accueil.qmd
            text: Accueil
          - href: doc/cours2A.qmd
            text: Cours de spécialisation 2A
          - href: doc/cours3A.qmd
            text: Les cours en Master
          - href: doc/examen-analyste.qmd
            text: L'examen d'Analyste
          - href: doc/deplacements.qmd
            text: Déplacements
          - href: doc/stage.qmd
            text: Le Stage
      - text: L'INSEE
        menu:
          - href: doc/INSEE.qmd
            text: Focus sur l'INSEE
          - href: doc/DSI.qmd
            text: la DSI
    right:
      - icon: github
        href: "{{< meta var.url-repo >}}"
        target: "_blank"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Code source]({{< meta var.url-repo >}}){.external target="_blank"}

format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
