---
title: "Accueil Master STD"
subtitle: "Rentrée Master Statistique et Traitement des Données"
author: "Ludovic Deneuville"
date: "9 septembre 2024"
format:
  revealjs:
    theme: moon
    footer: "[Home](../index.html)"      # Link to the homepage
    slide-number: c/t                    # collapsed/total
    chalkboard: true
    controls: true
from: markdown+emoji
---

## UE et Matières

- Machine Learning
- Génie Logiciel, DevOps
- Big Data, Cloud
- Système, Réseaux, Sécurité
- Gestion de projet

:::{.notes}
Sans oublier l'anglais
:::

## Examen Analyste

- [Lien examen](https://www.economie.gouv.fr/recrutement/analyste-developpeur-examen-professionnel){target="_blank"}
- [Inscription](https://concours-sg.finances.gouv.fr/){target="_blank"}
- Pas obligatoire pour travailler en service Informatique à l'INSEE
  - mais fortement recommandé
- Prime analyste : 225€ / mois


## Examen Analyste

\

### Qualités évaluées

- Techniques d'analyse, 
- Aptitude à la synthèse
- Rédaction d'un dossier technique
- Connaissances en matière de programmation
- Qualités de réflexion et de logique


## Examen Analyste

\

### Connaissances

- Gestion de projet, organisation du SI
- Développement d'applications
- Matériel, sécurité, réseaux, architecture
- Environnement juridique et administratif


## Examen Analyste

\

### Dates

- inscriptions : mi-Octobre
- écrit (début janvier) : 6h
  - dossier d'analyse
- oral (début mars) : 30min prépa, 10 min exposé, 20min questions
  - tirage au sort de 2 sujets, choix d'un sujet



## Examen Analyste

\

### Prépa

- 4 Examens blancs écrits à l'ENSAI
- 3 Oraux blancs à l'IGPDE

::: {.notes}
OB1 le 4/12
:::

## Examen Analyste

\

### Mission

- OM Collectif
  - Avec Nuitée si oral avant 10h
  - Sans Nuitée si oral après 10h
- Remboursement de frais

::: {.notes}
Volontaire pour participer à réunion

Prévenir si situation particulière (n'habite pas Rennes)
:::


## Stage

[Infos stage](stage.qmd)

## INSEE

- [Focus INSEE](INSEE.qmd)
- Vérifiez vos accès à l'[intranet](https://intranet.insee.fr/){target="_blank"} et à [Mouv'in](https://mobilites.insee.fr/){target="_blank"}
  - la campagne de mobilité démarre en octobre


## Campagne de mobilité

\

### Dates importantes

- Mi-octobre : vous devez être inscrits dans la campagne
- Mi-décembre : diffusion des postes ouverts
- Fin-février : dépôt des voeux
- Mi-avril : résultats


## Campagne de mobilité

\

### Conseils

- [ ] préparez en avance votre CV
- [ ] préparez un mail de motivation
  - à adapter ensuite selon les postes visés
- [ ] envoyez des mails avant Noël
  - le 15 janvier c'est trop tard !


## Métiers INSEE {.smaller}

Avoir fait un poste dans la sphère info est un vrai plus

- Analyste Développeur
- Analyste Développeur confirmé
- Expert big data
- Chef de projet
- Urbaniste du système d'information
- DBA
- Ingénieur Système et Sécurité
- Ingénieur DevOps
- Ingénieur dans l’équipe produit Kubernetes
