---
title: "Examen d'Analyste"
description: "Préparation à l'examen d'Analyste Développeur"
author: "Ludovic Deneuville"
format:
  html:
    toc: true
    toc-location: left
    toc-expand: 3
from: markdown+emoji
---

## Présentation

Cet examen permet de valider vos connaissances dans le domaine du traitement de l'information. Sa réussite vous confére la qualification d'Analyste-développeur à vie.  

Cette qualification vous permet :

- d'obtenir une prime supplémentaire mensuelle si vous êtes affecté sur un poste informatique
- d'accéder aux qualifications PSE et Chef de projet 

Il y a 2 épreuves à réussir (note ≥ 10) pour obtenir la qualification :

- épreuve écrite : étude d'un cas d'automatisation + dossier technique
- épreuve orale : présentation d'un sujet tiré au sort, puis questions du jury

## Liens

- [Page examen](https://www.economie.gouv.fr/recrutement/analyste-developpeur-examen-professionnel){target="_blank"} (Calendrier, infos, annales, rapports du jury...)
- [Inscription](https://concours-sg.finances.gouv.fr/){target="_blank"}


## Contacts

| Contact            | Rôle                                        |
|--------------------|---------------------------------------------|
| BLOCH Fabrice      | Correspondant INSEE                         |
| BOURDIN Marion     | IGPDE - Chargée de formation cycle analyste |
| DENEUVILLE Ludovic | ENSAI - Responsable Master STD              |
| DUCHESNE Aurélie   | ENSAI - Organisatrice de la formation       |
|                    |                                             |


## Formateurs

| Formateur       | Matière                      |
|-----------------|------------------------------|
| KOUAME Sonia    | Préparation à l'examen écrit |
| BROSSARD Xavier | Gestion de projet            |
| MSELLEK Nadia   | Gestion de projet            |
| AALIOUI Bilal   |                              | 
|                 |                              |


## Examens blancs

### Écrits

:::: {.callout-important}
- Début : 10h
- Fin : 16h

Vous n'avez le droit à aucun document. Calculatrice de l'école autorisée.

En cas de sortie temporaire de la salle, vous serez toujours accompagné.

Vous pouvez apporter à manger (évitez les chips).
:::


L'IGPDE fournit les sujets et corrige les copies

- Examen Blanc n°1 du 15/09/24
- Examen Blanc n°2 du 18/10/24
- Examen Blanc n°3 du 15/11/24
- Examen Blanc n°4 du 13/12/24


### Oraux

Les oraux blancs ont lieu en présentiel à l'IGPDE :

::: {.callout-note title="Adresse et Trajet"}
IGPDE  
20, allée Georges Pompidou  
94300 VINCENNES  

- RER A (Vincennes) ou Metro 1 (Château de Vincennes)
- Depuis Montparnasse (35 min)
  - Métro 4 :arrow_right: Chatelet Les Halles :arrow_right: RER A
:::

- Oral Blanc n°1 du 04/12/24
- Oral Blanc n°2 du 27/01/25
- Oral Blanc n°3 du 19/02/25

::: {.callout-tip}
- Présenter convocation + une pièce d’identité pour accéder au batiment
- Restaurant administratif dans le batiment ouvert de 11h45 à 14h00 (présenter convocation pour avoir un tarif réduit)
- Espace convivialité au 3ème étage, cafétéria au rdc, centre de documentation au 4ème étage
:::

#### Déroulement d'un oral

1. Tirage au sort des sujets 
	- Bureau 7120 (Christine Gaillard et Marion Bourdin) 
	- 5 minutes avant le début de votre préparation (ex : 8h55 si début à 9h) 
2. Préparation de votre présentation 
	- à la salle indiquée sur le planning
	- durée : 30 minutes
	- Du brouillon est à disposition. Pensez à prendre une montre ou un chronométre
3. Passage devant le jury + débriefing :
	- Salle indiquée sur les plannings
	- 10 minutes de présentation (bien respecter le temps imparti !)
	- 20 minutes de questions-réponses  
	- 20 minutes de débriefing  



---

## Examen

Chauqe année, 2 sessions d'examen sont programmées.

### Calendrier 2025 

#### 1ere session

|||
|----------------------------|------------------------|
| Ouverture des inscriptions | 10/10/2024             |
| Clôture des inscriptions   | 14/11/2024             |
| Épreuve écrite             | 16/01/2025             |
| Résultats Admissibilité    | 13/02/2025             |
| Épreuve orale              | À partir du 10/03/2025 |


#### 2e session

:construction:

### Écrit

::: {.callout-note title="Adresse et Trajet"}
Centrex  
2 Rue de la Butte Verte  
93160 NOISY-LE-GRAND  

- RER A Noisy-Champs
- Depuis Montparnasse (50min)
  - Métro 4 :arrow_right: Chatelet Les Halles :arrow_right: RER A :arrow_right: Noisy Champs
:::

- Jeudi 11 janvier 2024
  - Début de l'épreuve : 9h45
  - Fin de l'épreuve : 15h45


### Oral

- À partir du 11 mars 2024

::: {.callout-note title="Adresse et Trajet"}
Immeuble Atrium  
Place des Vins-de-France  
75573 PARIS
:::


## Semaine à la DG

- Lundi 12/02: préparation à l’oral J1 [Bilal Aalioui et Nadia Msellek]
- Mardi 13/02 : l’informatique ministérielle et interministérielle [Bilal aalioui et Nadia Msellek]
- Mercredi 14/02 : Oraux Blancs n°3 à l'IGPDE
- Jeudi 15/02 : préparation à l’oral J2 [Bilal Aalioui et Nadia Msellek]
- Vendredi 16/02 : days of chaos [Armelle Koehl Donatien Eneman]


## Missions

::: {.callout-caution}
Vous aurez 2 types de missions différents qui ne donnent pas lieu aux mêmes prises en charge :

- `formation` (oraux blanc, semaine DG) :arrow_right: tous les frais sont pris en charge : transport, repas, nuitées
- `concours / examens` (examens écrit et oral) :arrow_right: seul le transport aller/retour est remboursé par l'ENSAI

:::

### Ordre de Mission

Avant de partir en mission, il est impératif d'être couvert par un `Ordre de Mission` (OM).

Pour obtenir cet OM, vous devez préalablement remplir une `demande d'OM`, au plus tard 10 jours avant le début de la mission. Cette fiche liste tous les élèments permettant de définir la mission :

- Nom, prénom, tél, mail
- Lieu de départ, dates de départ et de retour
- Motif, lieu et durée de la mission
  - il faut joindre un justificatif de mission (convocation, justificatif d'inscription...)
- Détailler les trajets pour se rendre sur le lieu de la mission (pas besoin de détailler métro, rer, bus)
- Signer, et faire signer par la direction des études [ET]{.underline} le secrétariat général

Une fois que tout est bien rempli, vous pouvez envoyer votre demande d'OM et la convocation sur la boite fonctionnelle *mission*.

::: {.callout-important title="Cochez les bonnes cases"}
Vous avez 2 possibilités pour vos billets de train :

1. Vous achetez vous-même les billets et demanderez ensuite le remboursement
  - Billet à commander : NON
  - Billet à rembourser : OUI
2. Vous demander à l'ENSAI de commander vos billets
  - Billet à commander : OUI
  - Billet à rembourser : NON
  - dans ce cas, votre demande d'OM doit arriver au minimum 15 jours avant le début de la mission

Cochez la case *Metro / RER / Bus* si nécessaire pour votre trajet.
:::


### Remboursement de frais

Il est important de demander et conserver tous les justificatifs originaux de frais (ticket repas, ticket métro, facture hôtel...).

A votre retour de mission, envoyez sans tarder le tout aux gestionnaires.


- Repas
  - Si arrivée la veille : repas du soir : 20€
  - Le midi :
    - 10€ si repas dans un restaurant administratif
    - 20€ si repas à l'extérieur
  - Si retour de mission après 20h, repas du soir : 20€