---
title: "Présentation Master STD"
subtitle: "Master Statistique et Traitement des Données"
author: "Ludovic Deneuville"
date: "2025.03.17"
format:
  revealjs:
    theme: moon
    footer: "[Home](../index.html)"      # Link to the homepage
    slide-number: c/t                    # collapsed/total
    chalkboard: true
    controls: true
revealjs-plugins:
  - confetti
from: markdown+emoji
---

## Sommaire

- La DSI de l'INSEE
- Matières étudiées à l'ENSAI
- Technologies
- DevOps

## But de l'informatique

::: {.callout-important}
- Améliorer l'efficacité
- Gérer et protéger des données
- Répondre à des besoins métier
:::

:::{.notes}
- Supprimer des tâches sans valeur ajoutée
- Répondre à des besoins utilisateurs, les conseiller
:::

## DSI de l'INSEE

- Développement d'applications
- Production, Infrastructure, Architecture, Réseaux
- Sécurité, Stratégie
- **Innovation**, État de l'art

::: {.notes}

- WEB4G : insee.fr
- RESIL : répertoire Statistique des Individus et des Logements
- SIRENE : répertoire d'entreprises
- NAUTILE : tirage d'échantillon
- METALLICA : enquêtes ménages (conception, suivi, collecte)

plus de 100 applications (gestion de répertoire, intégration de fichiers, organisation, outils internes)
:::


## DSI de l'INSEE

- Effectifs 2022 : 428 
  - effectifs INSEE 2022 : 5027 
  - 240 développeurs et développeuses
- Paris, Nantes, Lille, Orléans, Metz...


::: {.notes}
Plus d'hommes que de femmes mais elles sont souvent très motivées, efficaces.

Pas là pour enfiler des perles
:::

## Exemple de métiers à l'INSEE

- Analyste développeur
- Chef de projet informatique
- Architecte applicatif
- Analyste Sécurité


## Domaines étudiés en STD

- Génie Logiciel, DevOps
- Big Data, Cloud
- Système, Réseaux, Sécurité, Linux
- Machine Learning
- Gestion de projet

::: {.notes}
:dart: avoir une culture informatique

Intervenants venant du monde professionnel

Examen Analyste
:::

## Technologies clés

- Java : back
  - Python : ça arrive...
- JavaScript React : front
- Git, GitLab, GitHub
- CI/CD, Qualimétrie
- Docker, Kubernetes : Conteneurisation, Orchestration


::: {.notes}
Avant tout ça :

- coder sur sa machine
- lancer les tests
- créer un zip
- se connecter au serveur de dev, arrêter
- déposer le zip, redémarrer

ça marche sur ma machine et pas sur le serveur...
:::


## DevOps à l’Insee 

- Initiée par la DSI en 2021
- Aller plus loin que SCRUM 
  - augmenter le rythme des déploiements

::: {.notes}
Méthodes agiles applicables aussi aux projets stats
:::

## DevOps à l’Insee 

- Fluidifier les interactions entre développeurs (dev) et exploitants (ops)
- Automatiser le processus de mise en production
  - CI/CD, Conteneurisation
- Tests automatisés pour contrôler
- Outils d'observations de la prod aux développeurs

::: {.notes}
Dashboard
:::

## DataOps

- Fluidifier le lien entre :
  - Gestionnaires de données
  - Consommateurs de données


## Conclusion

- Un poste à l'info est un vrai plus
- Innovation, Dynamique
- Communauté très active
- Pas besoin d'être un crack en informatique
- Vision globale de ce que fait l'INSEE

::: {.notes}
Confettis : press C
:::
