---
title: "Stage Master STD"
author: "Ludovic Deneuville"
description: "[Format Slide](stage-slide.html)"
format:
  html:
    toc: true
    toc-location: left
    toc-expand: 3
    css: none
  revealjs:
    theme: moon
    footer: "[Home](../index.html) - [Stage Master STD](stage.qmd)"      # Link to the homepage
    slide-number: c/t                    # collapsed/total
    slide-level: 3
    chalkboard: true
    controls: true
    output-file: stage-slide.html
from: markdown+emoji
---

## Modalités :memo:

- durée : entre 20 semaines et 6 mois
- entre le 3 mars et le 31 août


## Objectifs :dart: 

- Mobiliser les connaissances acquises à l'ENSAI 
- Mise en situation professionnelle réelle
- Comprendre le fonctionnement de la structure d'accueil
- Travailler au sein d'une équipe
- Gagner en autonomie
- Prendre des initiatives, explorer des technologies émergentes


## Contenu :gem:

En lien avec les enseignements de la filière STD :

- Machine Learning (Deep Learning, NLP)
- Développement / Déploiement d'une application
- Big Data, Cloud, DataOps
- Système, Réseaux et Sécurité

::: {.callout-note}
Il est préférable de travailler sur des domaines connus et ensuite d'aller plus loin.

Plutôt que de partir directement sur des sujets trop exotiques.
:::



### Exemples de sujets de stages {.smaller}

- L'intelligence artificielle au profit de la détection de sorties de données frauduleuses
- Identifier, analyser et prototyper une solution d’architecture pour exposer les services autour des métadonnées
- Construction d’un moteur d’agrégation de données individuelles utilisable en interactif
- Optimisation du calcul des populations légales à travers une architecture de calcul distribué
- Automatisation de la transformation des données individuelles pour la diﬀusion européenne
- Développement d’une application mobile pour les enquêteurs
- OpenSource et Modularité à l'INSEE : Exemple avec l'implémentation d'une méthode d'échantillonage
- Comment proposer une architecture conteneurisée pour répondre aux besoins de services en « self-déploiement » et d'intégration continue ?


## Étapes :hourglass:

1. Recherche bibliographique
2. Rencontrer les acteurs (Utilisateurs, MOA, Experts...)
3. Problématique
4. Expériences, analyses
5. Mise en valeur des résultats


### Réalisations attendues

Par exemple :

- Un produit viable
- Des résultats d'une expérience
- Un déploiement sur la plateforme dev.insee.io


## Les acteurs :tophat: 

### Maitre de stage 

- Définit les objectifs
- Assure un encadrement technique 
- Optimise les conditions de réalisation du stage
- Facilite l'intégration du stagiaire dans l'équipe
- Assure un suivi régulier de la progression du stagiaire
- Réalise un entretien de fin de stage
- Renseigne la grille d’évaluation


### Référent pédagogique 

- Un enseignant de l’ENSAI
- S'assure du bon déroulement du stage
- Point d'avancement de vos travaux en Mai


## Livrables :truck:

- Mi-mai : Note d'étape
- Fin août : Rapport final + Note de synthèse en anglais
- Mi-sept : Soutenance

### Note d'étape

- avant la fin du 2e mois, pour vérifier que tout va bien
- note de 2 à 3 pages en anglais ou français
- décrire votre mission (environnement, objectifs, résultats attendus...)
- le timing prévisionnel des différentes étapes
- méthodologies utilisées (ou qui seront mobilisées)
- état actuel de vos travaux


## Rapport :blue_book:

- 30 pages maximum hors annexes

:::{.notes}
Suivre un cheminement logique :

- d'où vous partez
- où vous voulez aller
- votre voyage
- là ou vous êtes arrivé
  - les nouveaux chemins qui s'ouvrent
:::

### Introduction

- Présentation du contexte
- Objectifs et Enjeux
- Description de la Mission
- Problématique
- Annonce du plan

### Partie 1 : Contexte

Commencez par décrire le contexte :

- Dans quoi s'intègre votre travail ?
- Pourquoi ce sujet est intéressant ?
- Quel est l'existant ?
- Gain pour l'établissement

### Conclusion

- Bilan et retours d'expérience
- Analyse Critique
- Perspectives et Projets Futurs

::: {.callout-important}
Conclusion ≠ Introduction
:::

### Bibliographie

::: {.callout-tip title="Objectif"}
Réalisez un état de l'art sur votre sujet.

Montrez-nous que vous avez pris de la hauteur !
:::

- Documentations officielles
- Articles de recherche, de blog
- Livres
- Conférences


### Démarche scientifique

Adoptez une démarche scientifique :

1. Observations
2. Formulation d'hypothèses
3. Expérimentations
4. Analyse des résultats
5. Conclusions


### Et les Stats ?

- Ne vous forcez pas à mettre des stats si elles ne servent à rien
- Par contre, il faut savoir répondre à une question de stat lors de la soutenance


## Note de synthèse :guardsman:

- En anglais
- 4 pages maximum

## Soutenance :tada:

- Exposé : 20 min
- Questions : 25 min

::: {.callout-note}
La soutenance se déroulera en présence :

- d'un président de jury
- de l'encadrant pédagogique de l'ENSAI
- du maitre de stage
:::


## Erreurs à éviter :warning:

### Erreur 1 : ne pas alerter

N'attendez pas la note d'étape et encore moins le dernier mois pour dire que ça ne va pas !

1. Discutez avec votre tuteur
2. Contactez votre référent ENSAI


### Erreur 2 : Ignorer le métier

::: {.callout-important}
Un développeur rend service à des utilisateurs.

Il faut donc apprendre le contexte métier dans lequel vous travaillez.
:::


### Erreur 3 : Contexte INSEE

Trop faible connaissance du contexte INSEE (ou de la structure d'accueil)

Solutions :

- Discuter avec les développeurs
- S'abonner aux canaux actifs sur Tchap
- Aller aux dev'académy, séminaires de développement...

### Erreur 4 : négliger le rapport

- Respectez le format attendu
- Donnez des titres informatifs à vos parties
- **RELISEZ-LE !!!!!**

::: {.callout-important title="Les figures"}
Les figures doivent être propres, lisibles avec un titre et une source.

Si vous utilisez une image, vérifiez qu'elle est libre de droits.
:::

---

::: {.callout-warning title="Erreurs à ne pas faire"}
- Rédiger son rapport une fois le stage terminé
- Utiliser "on" et la forme passive (ex : "on voit que")
- Insérer des figures sans aucune explication
:::

### Mise en valeur

Vous n'arrivez pas à montrer ce que vous avez fait :

- Manque de hauteur : vous utilisez des outils sans les comprendre
- Manque de technique : vous ne connaissez pas des notions de base


### Stage "prise de poste"

::: {.callout}
Vous devez réaliser un stage de niveau Master 2 sur un sujet bien précis.

Le but n'est pas que vous découvriez votre futur environnement de travail et appreniez à être opérationnel sur votre futur poste.

Ce n'est pas interdit mais cela pourrait vous pénaliser.

Le but lorsque vous intégrez une équipe n'est pas de vous conformer à son mode de fonctionnement sans avoir un esprit critique. 
Vous êtes jeunes et plein d'énergie, vous devez apporter de nouvelles pratiques et techniques.
:::



## Liens utiles :link: 

- [pass fonction publique](https://www.pass.fonction-publique.gouv.fr/){target="_blank"}
- Offres de stage sur Moodle


## Pour terminer :checkered_flag: 

- Produisez quelque chose dont vous êtes fier
- Produisez un travail sérieux
- Creuser les sujets qui vous paraissent interessants




<style>
  .description{
    text-align: right
  }

  h2::before {
    content: none
  }
  
  h3::before {
    content: none
  }
  
  h4::before {
    content: none
  }
  
  .header-section-number:after {
    content: none
  } 
</style>